namespace calc.Common.Styles
{
    public enum ThemeResourceKey
    {
        ContentBackground,
        ContentForeground,
        ControlForeground,
        ControlBorder,
        ControlBackground,
        ControlContentBackground,
        ControlDefaultBorder,
        ControlHighlightBackground,
        ControlMouseOverBackground,
        ControlMouseOverBorder,
        ControlPressedBackground,
        ControlPressedBorder,
        ControlDisabledOpacity,
        ControlFocusBorder,
        GlyphForeground,
        GroupBoxHeaderBorder,
        GroupBoxHeaderForeground,
        ListMouseOverBackground,
        ListMouseOverBorder,
        ListSelectedBackground,
        ListSelectedBorder,
        ListSelectedForeground,
        WindowBorder,
        WindowActiveBorder,
        WindowControlMouseOverBackground,
        WindowHeaderBackground,
        WindowHeaderForeground
    }
}
